- name: Generate GitHub Stats
  uses: stats-organization/github-readme-stats-action@v2
  with:
    card: stats
    options: username=hemrajmeena073&show_icons=true&theme=tokyonight&hide_border=true
    path: profile/stats.svg
    token: ${{ secrets.GH_TOKEN }}
    fail_on_error: true

- name: Generate Top Languages
  uses: stats-organization/github-readme-stats-action@v2
  with:
    card: top-langs
    options: username=hemrajmeena073&layout=compact&langs_count=8&theme=tokyonight&hide_border=true
    path: profile/top-langs.svg
    token: ${{ secrets.GH_TOKEN }}
    fail_on_error: true
